MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r

CREATE  (A:PAIS{name:'ECUADOR', numero: 0}),
	    (B:CIUDAD{name:'Quito', numero: 1}),
	    (C:CIUDAD{name:'Guayaquil', numero: 2}),
	    (D:CIUDAD{name:'Cuenca', numero: 3}),
	    (E:CIUDAD{name:'Santo Domingo', numero: 4}),
	    (F:CIUDAD{name:'Machala', numero: 5}),
	    (G:CIUDAD{name:'Durán', numero: 6}),
	    (H:CIUDAD{name:'Portoviejo', numero: 7}),
	    (I:CIUDAD{name:'Manta', numero: 8}),
	    (J:CIUDAD{name:'Loja', numero: 9}),
	    (K:CIUDAD{name:'Zamora', numero: 10}),

	    (A1:hijos1{name:'Parques', numero: 1}),
	    (B1:hijos1{name:'Iglesias', numero: 2}),
	    (D1:hijos1{name:'Hospitales', numero: 3}),
	    (E1:hijos1{name:'Bomberos', numero: 4}),
	    (F1:hijos1{name:'Policias', numero: 5}),
	    (G1:hijos1{name:'Esculeas', numero: 6}),
	    (H1:hijos1{name:'Lugares Tusisticos', numero: 7}),

	    (A2:hijos2{name:'Parques', numero: 1}),
	    (B2:hijos2{name:'Iglesias', numero: 2}),
	    (D2:hijos2{name:'Hospitales', numero: 3}),
	    (E2:hijos2{name:'Bomberos', numero: 4}),
	    (F2:hijos2{name:'Policias', numero: 5}),
	    (G2:hijos2{name:'Esculeas', numero: 6}),
	    (H2:hijos2{name:'Lugares Tusisticos', numero: 7}),

	    (A3:hijos3{name:'Parques', numero: 1}),
	    (B3:hijos3{name:'Iglesias', numero: 2}),
	    (D3:hijos3{name:'Hospitales', numero: 3}),
	    (E3:hijos3{name:'Bomberos', numero: 4}),
	    (F3:hijos3{name:'Policias', numero: 5}),
	    (G3:hijos3{name:'Esculeas', numero: 6}),
	    (H3:hijos3{name:'Lugares Tusisticos', numero: 7}),

	    (A4:hijos4{name:'Parques', numero: 1}),
	    (B4:hijos4{name:'Iglesias', numero: 2}),
	    (D4:hijos4{name:'Hospitales', numero: 3}),
	    (E4:hijos4{name:'Bomberos', numero: 4}),
	    (F4:hijos4{name:'Policias', numero: 5}),
	    (G4:hijos4{name:'Esculeas', numero: 6}),
	    (H4:hijos4{name:'Lugares Tusisticos', numero: 7}),

	    (A5:hijos5{name:'Parques', numero: 1}),
	    (B5:hijos5{name:'Iglesias', numero: 2}),
	    (D5:hijos5{name:'Hospitales', numero: 3}),
	    (E5:hijos5{name:'Bomberos', numero: 4}),
	    (F5:hijos5{name:'Policias', numero: 5}),
	    (G5:hijos5{name:'Esculeas', numero: 6}),
	    (H5:hijos5{name:'Lugares Tusisticos', numero: 7}),

	    (A6:hijos6{name:'Parques', numero: 1}),
	    (B6:hijos6{name:'Iglesias', numero: 2}),
	    (D6:hijos6{name:'Hospitales', numero: 3}),
	    (E6:hijos6{name:'Bomberos', numero: 4}),
	    (F6:hijos6{name:'Policias', numero: 5}),
	    (G6:hijos6{name:'Esculeas', numero: 6}),
	    (H6:hijos6{name:'Lugares Tusisticos', numero: 7}),

	    (A7:hijos7{name:'Parques', numero: 1}),
	    (B7:hijos7{name:'Iglesias', numero: 2}),
	    (D7:hijos7{name:'Hospitales', numero: 3}),
	    (E7:hijos7{name:'Bomberos', numero: 4}),
	    (F7:hijos7{name:'Policias', numero: 5}),
	    (G7:hijos7{name:'Esculeas', numero: 6}),
	    (H7:hijos7{name:'Lugares Tusisticos', numero: 7}),

	    (A8:hijos8{name:'Parques', numero: 1}),
	    (B8:hijos8{name:'Iglesias', numero: 2}),
	    (D8:hijos8{name:'Hospitales', numero: 3}),
	    (E8:hijos8{name:'Bomberos', numero: 4}),
	    (F8:hijos8{name:'Policias', numero: 5}),
	    (G8:hijos8{name:'Esculeas', numero: 6}),
	    (H8:hijos8{name:'Lugares Tusisticos', numero: 7}),

	    (A9:hijos9{name:'Parques', numero: 1}),
	    (B9:hijos9{name:'Iglesias', numero: 2}),
	    (D9:hijos9{name:'Hospitales', numero: 3}),
	    (E9:hijos9{name:'Bomberos', numero: 4}),
	    (F9:hijos9{name:'Policias', numero: 5}),
	    (G9:hijos9{name:'Esculeas', numero: 6}),
	    (H9:hijos9{name:'Lugares Tusisticos', numero: 7}),

	    (A11:hijos11{name:'Parques', numero: 1}),
	    (B11:hijos11{name:'Iglesias', numero: 2}),
	    (D11:hijos11{name:'Hospitales', numero: 3}),
	    (E11:hijos11{name:'Bomberos', numero: 4}),
	    (F11:hijos11{name:'Policias', numero: 5}),
	    (G11:hijos11{name:'Esculeas', numero: 6}),
	    (H11:hijos11{name:'Lugares Tusisticos', numero: 7}),

         (A)-[:CONNECTION{}]->(B),
         (A)-[:CONNECTION{}]->(C),
         (A)-[:CONNECTION{}]->(D),
         (A)-[:CONNECTION{}]->(E),
         (A)-[:CONNECTION{}]->(F),
         (A)-[:CONNECTION{}]->(G),
         (A)-[:CONNECTION{}]->(H),
         (A)-[:CONNECTION{}]->(I),
         (A)-[:CONNECTION{}]->(J),
         (A)-[:CONNECTION{}]->(K),

         (B)-[:CONNECTION{}]->(A1),
         (B)-[:CONNECTION{}]->(B1),
         (B)-[:CONNECTION{}]->(D1),
         (B)-[:CONNECTION{}]->(E1),
         (B)-[:CONNECTION{}]->(F1),
         (B)-[:CONNECTION{}]->(G1),
         (B)-[:CONNECTION{}]->(H1),

         (C)-[:CONNECTION{}]->(A2),
         (C)-[:CONNECTION{}]->(B2),
         (C)-[:CONNECTION{}]->(D2),
         (C)-[:CONNECTION{}]->(E2),
         (C)-[:CONNECTION{}]->(F2),
         (C)-[:CONNECTION{}]->(G2),
         (C)-[:CONNECTION{}]->(H2),

        (D)-[:CONNECTION{}]->(A3),
        (D)-[:CONNECTION{}]->(B3),
        (D)-[:CONNECTION{}]->(D3),
        (D)-[:CONNECTION{}]->(E3),
        (D)-[:CONNECTION{}]->(F3),
        (D)-[:CONNECTION{}]->(G3),
        (D)-[:CONNECTION{}]->(H3),

        (E)-[:CONNECTION{}]->(A4),
        (E)-[:CONNECTION{}]->(B4),
        (E)-[:CONNECTION{}]->(D4),
        (E)-[:CONNECTION{}]->(E4),
        (E)-[:CONNECTION{}]->(F4),
        (E)-[:CONNECTION{}]->(G4),
        (E)-[:CONNECTION{}]->(H4),

        (F)-[:CONNECTION{}]->(A5),
        (F)-[:CONNECTION{}]->(B5),
        (F)-[:CONNECTION{}]->(D5),
        (F)-[:CONNECTION{}]->(E5),
        (F)-[:CONNECTION{}]->(F5),
        (F)-[:CONNECTION{}]->(G5),
        (F)-[:CONNECTION{}]->(H5),

        (G)-[:CONNECTION{}]->(A6),
        (G)-[:CONNECTION{}]->(B6),
        (G)-[:CONNECTION{}]->(D6),
        (G)-[:CONNECTION{}]->(E6),
        (G)-[:CONNECTION{}]->(F6),
        (G)-[:CONNECTION{}]->(G6),
        (G)-[:CONNECTION{}]->(H6),

        (H)-[:CONNECTION{}]->(A7),
        (H)-[:CONNECTION{}]->(B7),
        (H)-[:CONNECTION{}]->(D7),
        (H)-[:CONNECTION{}]->(E7),
        (H)-[:CONNECTION{}]->(F7),
        (H)-[:CONNECTION{}]->(G7),
        (H)-[:CONNECTION{}]->(H7),

        (I)-[:CONNECTION{}]->(A8),
        (I)-[:CONNECTION{}]->(B8),
        (I)-[:CONNECTION{}]->(D8),
        (I)-[:CONNECTION{}]->(E8),
        (I)-[:CONNECTION{}]->(F8),
        (I)-[:CONNECTION{}]->(G8),
        (I)-[:CONNECTION{}]->(H8),

        (J)-[:CONNECTION{}]->(A9),
        (J)-[:CONNECTION{}]->(B9),
        (J)-[:CONNECTION{}]->(D9),
        (J)-[:CONNECTION{}]->(E9),
        (J)-[:CONNECTION{}]->(F9),
        (J)-[:CONNECTION{}]->(G9),
        (J)-[:CONNECTION{}]->(H9),

        (K)-[:CONNECTION{}]->(A11),
        (K)-[:CONNECTION{}]->(B11),
        (K)-[:CONNECTION{}]->(D11),
        (K)-[:CONNECTION{}]->(E11),
        (K)-[:CONNECTION{}]->(F11),
        (K)-[:CONNECTION{}]->(G11),
        (K)-[:CONNECTION{}]->(H11)